import type { ProjectPhase, SkillKey, Skills } from "@/lib/db-api"

export type RoleRequirement = {
  role_name: string
  count: number
  required_skills: Skills
  reasoning: string
}

export type StaffingSuggestion = {
  roles: RoleRequirement[]
  summary: string
  total_headcount: number
}

export type SkillProfileSuggestInput = {
  projectId?: number
  github_repo_url: string
  project_phase: ProjectPhase
  task_description?: string | null
}

type SkillProfileResponse = {
  required_people_amount: number
  required_skills_per_person: Skills[]
}

const backendApiBasePath = "/api"

export class BackendApiError extends Error {
  constructor(
    message: string,
    readonly status: number
  ) {
    super(message)
    this.name = "BackendApiError"
  }
}

async function fetchBackendApi<T>(
  path: string,
  init?: RequestInit
): Promise<T> {
  const response = await fetch(`${backendApiBasePath}${path}`, {
    ...init,
    headers: {
      Accept: "application/json",
      ...init?.headers,
    },
  })

  if (!response.ok) {
    throw new BackendApiError(
      `Backend API request failed with status ${response.status}`,
      response.status
    )
  }

  return response.json() as Promise<T>
}

export function suggestProjectRequirements(input: SkillProfileSuggestInput) {
  const projectId = input.projectId ?? 1

  return fetchBackendApi<SkillProfileResponse>("/skill-profile", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      project_id: projectId,
      github_page: input.github_repo_url,
      project_description: input.task_description ?? "",
    }),
  })
    .then(mapSkillProfileResponse)
    .catch((error) => {
      if (!(error instanceof BackendApiError) || error.status !== 404) {
        throw error
      }

      return fetchBackendApi<StaffingSuggestion>(
        `/projects/${projectId}/skill-profile:suggest`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            github_repo_url: input.github_repo_url,
            project_phase: input.project_phase,
            task_description: input.task_description,
          }),
        }
      )
    })
}

function mapSkillProfileResponse(response: SkillProfileResponse): StaffingSuggestion {
  return {
    roles: response.required_skills_per_person.map((skills, index) => ({
      role_name: `Suggested role ${index + 1}`,
      count: 1,
      required_skills: skills,
      reasoning: "Generated by the backend skill-profile service.",
    })),
    summary: "Backend-generated minimum staffing profile.",
    total_headcount: response.required_people_amount,
  }
}

export function suggestProjectRequirementsFromRepoRoute(
  input: SkillProfileSuggestInput
) {
  const projectId = input.projectId ?? 1

  return fetchBackendApi<StaffingSuggestion>(
    `/projects/${projectId}/skill-profile:suggest`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        github_repo_url: input.github_repo_url,
        project_phase: input.project_phase,
        task_description: input.task_description,
      }),
    }
  )
}

export const skillKeys: SkillKey[] = [
  "android",
  "ios",
  "web",
  "backend",
  "infrastructure",
  "ai",
]
